### ISSUE TITLE
Atom Snippet

### ISSUE THREAD

**Issue by Kmille267** [slu-soc5050/Week-03#1]
Hi @thbraswell & @chris-prener,

I'm having difficulty using adding the snippet to Atom. I think I accidentally deleted the default directions that come in the Atom Snippets window.  In the instructions, Chris indicated that we were to paste his snippet after the directions. In the event that the default directions do not matter, it may be that the Stata language package is not functioning properly. I am using both the snippet and language package, but when I type headmaster, nothing is displaying. Please advise when time permits. Until then, I will continue to do my analysis in a Stata .do file.

**Comment by chris-prener** [comment]
Hi @Kmille267 ,
Just to double check - you have the document's language turned to Stata, correct?

It sounds like there is an error in the snippets file, though I do not think it is related to the template. Just do the assignment in a straight do-file and we'll take a look at your laptop on Monday.

cheers,
@chris-prener

**Comment by Kmille267** [comment]
Hi @chris-prener, 

I had installed the language for Stata last week, but I hadn't tried it. It is absolutely possible that something wrong occurred in the installation. However, I did uninstall and reinstall the package.

Sounds good. I'm sorry for all of the trouble.

Thanks,
@Kmille267

**Comment by chris-prener** [comment]
Hi @Kmille267 ,
Are you able to change the language of a file to Stata? If so, the issue is not with the `language-stata` package.

In that case, the issue is likely with your snippets file. I would delete the entire contents, and re-copy and paste the text from the `stata-snippets.cson` file.

See if that helps and then let me know. It is no trouble at all.

cheers,
@chris-prener

**Comment by Kmille267** [comment]
Hi @chris-prener, 
I believe that I have changed the language. When I quote the commands as you had done in the lecture, the text turns purple.  I have tried copying and changing the snippet text to no avail.

**Comment by chris-prener** [comment]
Hi @Kmille267 ,
Can't say for sure but it sounds like the language package is installed correctly. My hunch is that you are not copying the entirety of the snippets file. Or something is getting lost along the way. Lets touch base on Monday about this. 

In the meantime, I still want you to use the do-file stack we have been building up to this week. Take the lab replication for this week and use that as a starting point. Delete the code from the lab and fill in the code for the problem set.

cheers,
@chris-prener
